### ISSUE TITLE
Error while registering publisher /rosout: Connection refused

### ISSUE THREAD

**Issue by GSORF** [TimWhiting/dartros#46]
Hi,

Thank you for providing this interesting flutter package to enable communication with ROS.

I am trying to get a minimal example working. I have composed the following code from the given examples:

```
import 'package:dartros/dartros.dart';
import 'package:dartx/dartx.dart';

Future<void> main(List<String> args) async {
  final node = await initNode('test_node', args);
  String master_uri = await node.getMasterUri();
  print(master_uri);
}
```

My hardware setup is as follow:

1. I have opened up a WIFI hotspot with my smartphone to which one of our linux laptops ("Lenovo ideapad" wired with a Turtlebot 2) is connected. I have started "roscore" on the terminal. I am using ROS Kinetic, version 1.12.13. ROS_MASTER_URI, ROS_HOSTNAME and ROS_IP are all set pointing to local host. I am using the laptop as the ROS Master basically. I can ping the smartphone from the laptop.
2. I have my android smartphone running the flutter app from the examples. I am getting a connection refused error which can have a multitude of causes (firewall, IP config, signal deteoriation, etc.).

When trying this setup with the above code I am getting the following error traceback:

```
I/flutter (26591): │ Error while registering publisher /rosout: Connection refused
I/flutter (26591): │ #0      IOClient.send (package:http/src/io_client.dart:88:7)
I/flutter (26591): │ <asynchronous suspension>
I/flutter (26591): │ #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
I/flutter (26591): │ <asynchronous suspension>
I/flutter (26591): │ #2      call (package:xml_rpc/src/client.dart:49:7)
I/flutter (26591): │ <asynchronous suspension>
I/flutter (26591): │ #3      _rpcCall (package:dartros/src/ros_xmlrpc_client.dart:70:18)
I/flutter (26591): │ <asynchronous suspension>
I/flutter (26591): │ #4      RosXmlRpcClient.registerPublisher (package:dartros/src/ros_xmlrpc_client.dart:238:8)
I/flutter (26591): │ <asynchronous suspension>
I/flutter (26591): │ #5      PublisherImpl._register (package:dartros/src/impl/publisher_impl.dart:107:20)
I/flutter (26591): │ <asynchronous suspension>
I/flutter (26591): │ 
```

I will continue testing, but maybe I am doing something wrong here already. Do you have any ideas how I can test your dart package with as minimal code and hardware as possible?

Thanks for your time and kind regards,
Adam

**Comment by GSORF** [comment]
In case anyone else got the same problem: I tested the code with another setup. This time I was not using a hotspot from my phone but a dedicated router for the network connection. This worked! Hopefully it work for you, too.
